name: Publish to npm

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Publish NPM package
        run: npm publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
